/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_util_MessageHandler */

#ifndef _Included_at_o2xfs_xfs_util_MessageHandler
#define _Included_at_o2xfs_xfs_util_MessageHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef at_o2xfs_xfs_util_MessageHandler_MIN_PRIORITY
#define at_o2xfs_xfs_util_MessageHandler_MIN_PRIORITY 1L
#undef at_o2xfs_xfs_util_MessageHandler_NORM_PRIORITY
#define at_o2xfs_xfs_util_MessageHandler_NORM_PRIORITY 5L
#undef at_o2xfs_xfs_util_MessageHandler_MAX_PRIORITY
#define at_o2xfs_xfs_util_MessageHandler_MAX_PRIORITY 10L
/*
 * Class:     at_o2xfs_xfs_util_MessageHandler
 * Method:    run0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_util_MessageHandler_run0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_util_MessageHandler
 * Method:    close
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_util_MessageHandler_close
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
