/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_30_idc_SynchronizeCommand330Test */

#ifndef _Included_at_o2xfs_xfs_v3_30_idc_SynchronizeCommand330Test
#define _Included_at_o2xfs_xfs_v3_30_idc_SynchronizeCommand330Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_30_idc_SynchronizeCommand330Test
 * Method:    buildSynchronizeCommand330
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_130_idc_SynchronizeCommand3130Test_buildSynchronizeCommand3130
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
