/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_30_idc_EmvClessOutcome330Test */

#ifndef _Included_at_o2xfs_xfs_v3_30_idc_EmvClessOutcome330Test
#define _Included_at_o2xfs_xfs_v3_30_idc_EmvClessOutcome330Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_30_idc_EmvClessOutcome330Test
 * Method:    buildEmvClessOutcome330
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_130_idc_EmvClessOutcome3130Test_buildEmvClessOutcome3130
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
