/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_00_WfsVersionErrorTest */

#ifndef _Included_at_o2xfs_xfs_v3_00_WfsVersionErrorTest
#define _Included_at_o2xfs_xfs_v3_00_WfsVersionErrorTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_00_WfsVersionErrorTest
 * Method:    buildWfsVersionError
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_WfsVersionErrorTest_buildWfsVersionError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
