/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cdm_v3_00_StartEx3Test */

#ifndef _Included_at_o2xfs_xfs_cdm_v3_00_StartEx3Test
#define _Included_at_o2xfs_xfs_cdm_v3_00_StartEx3Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cdm_v3_00_StartEx3Test
 * Method:    buildStartEx3
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cdm_v3_100_StartEx3Test_buildStartEx3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
