/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_00_WfsHardwareError3Test */

#ifndef _Included_at_o2xfs_xfs_v3_00_WfsHardwareError3Test
#define _Included_at_o2xfs_xfs_v3_00_WfsHardwareError3Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_00_WfsHardwareError3Test
 * Method:    buildWfsHardwareError3
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_WfsHardwareError3Test_buildWfsHardwareError3
  (JNIEnv *, jobject);

/*
 * Class:     at_o2xfs_xfs_v3_00_WfsHardwareError3Test
 * Method:    buildDescriptionNull
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_WfsHardwareError3Test_buildDescriptionNull
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
