/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_00_WfsDevStatusTest */

#ifndef _Included_at_o2xfs_xfs_v3_00_WfsDevStatusTest
#define _Included_at_o2xfs_xfs_v3_00_WfsDevStatusTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_00_WfsDevStatusTest
 * Method:    buildWfsDevStatus
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_WfsDevStatusTest_buildWfsDevStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
