/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_00_WfsAppDisconnectTest */

#ifndef _Included_at_o2xfs_xfs_v3_00_WfsAppDisconnectTest
#define _Included_at_o2xfs_xfs_v3_00_WfsAppDisconnectTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_00_WfsAppDisconnectTest
 * Method:    buildWfsAppDisconnect
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_WfsAppDisconnectTest_buildWfsAppDisconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
