language: java
jdk:
  - oraclejdk8
branches:
  only:
    - develop
before_install:
 - chmod +x gradlew
script:
  - ./gradlew clean build publish -x test --continue --stacktrace
env:
  global:
    - ORG_GRADLE_PROJECT_maven_username=buildmaster
    - secure: URwKDeWbDyeUZxxqyLzJnsmrfR4CR74mVSX1ThFNWIiQa094LLr0mx/BlBzaYA9x+5guzfyDV6mHa7eUycrwWov2b1U9j7RJlCc7Z2M9J3MrZFywgFrk55dTqKJuwk4vAfGglP1Z5LaQBcEBE8zBSfyDn9tHVoTk6eNN7K8mwtvkgAv9rxXAy3VtmQ1d5OeN/k6o9GqjlJa5jgOH5Msud7qa7XJIv9k19YlCgMJWOjrJgucIzn+3xVuqRDh3GUNIK3ZQJQ8PcYd0v2D4oygLngkrCjufcx0T+fO0a6k9M5NinTbLZyhQZJ/kQZgKUiVok8rb8kxl5cSUBpRrjT9iE/3xXfgVx8G8XP6WAHvJc0E96e9qaK22pzgxUGQNLmeviqRt7RmIrOsCdaSSe69eYPteoJHOpXPYuppV81VcXEFM7orvZkOC6oRjYWl3yy2pekLCjL8LB13YX45osJo3EtTTdluGTPbbv8D0SD/hDEfJQ5hHHDodLSodlDTUhHr+O2LSmx6CyDuiESnjOYU+w9VhDW8G6Yetd7gYNd/OJbdU6rFJz29qD1TTrglDxLjieAZ1N2+9wgFqVvyxkCrfwZOzF+hgKIDGpm4YIA5Pkt5A/W9WwqpcyJFoOSKhuqhPdTxReZmZtGvHm+5wHUeAoB6LHiEhm/L+GnzGYVhKKks=