language: java
jdk:
  - oraclejdk8
branches:
  only:
    - develop
before_install:
 - chmod +x gradlew
script:
  - ./gradlew clean build publish -x test --continue --stacktrace
env:
  global:
    - ORG_GRADLE_PROJECT_maven_username=buildmaster
    - secure: KmxeCXKESVsPNM2zA6SSgv9xXpEjWJC+FYDR1xYJkaPGTqdaesuG2mYF7prOnqNJ0CEqeAZYdMniaJ5ig/CZghymGLH/nlFhU/aTF9zQTW8aJlkZH+q6nJYwEBXFeT6KShqsZECVa2C/m1XIsr0T0InNToRcB1CCFoMb8yZD6KbvKMYYJrn8DzTDC961x+ttaV18VcSxBFAIhIVXbDm1QF8svXRJK3V5iB0QlT8B5RXHe1hQllXpofMxg0kqjGxDuGNMNFikMwWm+SkWRYohv8yYVg66M5oz0Z4wuLZe5IpCU2utVsMq2z1CUDjjkWUD4qXIfNm/9A8iXKt+Ew5n/SJGqcUDVn7aguUULPp+NflGcA1jTeIAqNOjuhN8NQlidfkn2MjwEzPYDA+xK0n51bA2/740julv6dEXuL+49sD/bwkTyItveKEglOu3xJRjgRzkdfKwLfh60p35jYtHQ0DnSocS8tmhx9ZERUJiT5ikSYAIjMKKIvisDP/zpNxlvXKilHqDcZvrIJu5PVfCTH+EcGD4giKa8v1bfLGwcL/h/x11oDx8C8JnvbReqaVrrmID6S0/cyoY4fQMNA/nB3veKuRNEEo45bcYoJ/YuiT5/+ug0tWUzIT/CyL43O4hliSdkaMPqmEb9iJtY/PnH0a6VIbGgLYyf9cUmr8WP/E=