language: java
jdk:
  - oraclejdk8
branches:
  only:
    - develop
before_install:
 - chmod +x gradlew
script:
  - ./gradlew clean build publish -x test --continue --stacktrace
env:
  global:
    - ORG_GRADLE_PROJECT_maven_username=buildmaster
    - secure: IOj1bPo1Jb8Rkx1DLP8CSS2Ex0Z6knrEFnwGGGnUP6kYca6qyzhXxSpvmjgtX+7T2WU6EiR8nPp+sgDH3p7xC8U53DCqX1xOCceGmZ7PqiVGI9wqdH6hoMY7TBBi8l63fv1ltTapQX11RijremYGtB8Ok+brKe52AyfA5/06bvV84qH2PtdFSO5gZilzcLk74X18EemiO/Po1lOrdyYk+Egcny/E292ZJ5ZmTc+avlwdHhVtxbz4A1ylsUsAll8fSUfVLeiMIgyNvra0Utj8nopcl0eNCJ9LzGDFrszJMXisrNrqQk4KfwXgARwJuX9//rFM62fmTKD28uKJYrVlrTioqSJnVLpTary73mCGyUV63GKRqczgaKBAoUu3qIqpFpwnSlaesMc67UuBXlosNywxeuXOBL9grCbcVnzqqJbgJR38X9RNsdiyxayGwuLZMO7qlyhnontQXdcdndm/5ceaQeH+nZJXlXNiKu1WH/AESY1KVM9Bl+V+FZJUjEpAahwjnFoOL7FRdysoicFIE8cNRpc9zhYzLgibmrnGnRbJdEU1/fd+LGjRtF4RWK8YowvQbnWqBMwYAvn1043nb/7GPjBOOMKs90jaV3G15mg2bvo1du0P2WExDALSy1fOU8vkR3zAs5TlQga+fMxO0wwajltH7RhtMCxI7OzPMpA=