# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: O²Xfs Framework
email: o2xfs@fagschlunger.co.at
description: "" # this means to ignore newlines until "baseurl:"
baseurl: "/O2Xfs" # the subpath of your site, e.g. /blog
url: "http://AndreasFagschlunger.github.io/O2Xfs/" # the base hostname & protocol for your site
github_username:  AndreasFagschlunger

# Build settings
markdown: kramdown