branches:
  only:
    - develop

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  ORG_GRADLE_PROJECT_maven_username: buildmaster
  ORG_GRADLE_PROJECT_maven_password:
    secure: 5tyikQFuCQgJXFduL6baTVKw+pGrAkRd70TjT82xE+c=

install:
  - ps: .\xfs-sdk.ps1

build_script:
  - cmd: .\gradlew.bat -b at.o2xfs.win32\build-native.gradle clean build publish
  - cmd: .\gradlew.bat -b at.o2xfs.xfs\build-native.gradle clean build publish -PxfsSdkDir="C:/XFS SDKs/SDK303/Common/XFS/SDK"
  - cmd: .\gradlew.bat -b o2xfs-xfs3\build-native.gradle clean build publish -PXFS_SDK300="C:/XFS SDKs/SDK303/Common/XFS/SDK" -PXFS_SDK310="C:/XFS SDKs/SDK310/Common/XFS/SDK" -PXFS_SDK320="C:/XFS SDKs/SDK320/XFS/SDK" -PXFS_SDK330="C:/XFS SDKs/SDK330/XFS/SDK"
  - cmd: .\gradlew.bat -b at.o2xfs.ctapi\build-native.gradle clean build publish
  - cmd: .\gradlew.bat clean build publish
