/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cam_v320_CamStructTest */

#ifndef _Included_at_o2xfs_xfs_cam_v320_CamStructTest
#define _Included_at_o2xfs_xfs_cam_v320_CamStructTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cam_v320_CamStructTest
 * Method:    createCamStatus
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cam_v320_CamStructTest_createCamStatus
  (JNIEnv *, jobject);

/*
 * Class:     at_o2xfs_xfs_cam_v320_CamStructTest
 * Method:    createCamCaps
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cam_v320_CamStructTest_createCamCaps
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
