/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cam_v320_CamStructV3_20Test */

#ifndef _Included_at_o2xfs_xfs_cam_v320_CamStructV3_20Test
#define _Included_at_o2xfs_xfs_cam_v320_CamStructV3_20Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cam_v320_CamStructV3_20Test
 * Method:    createCamStatusV3_20
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cam_v320_CamStructV3_120Test_createCamStatusV3_120
  (JNIEnv *, jobject);

/*
 * Class:     at_o2xfs_xfs_cam_v320_CamStructV3_20Test
 * Method:    createCamCapsV3_20
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cam_v320_CamStructV3_120Test_createCamCapsV3_120
  (JNIEnv *, jobject);

/*
 * Class:     at_o2xfs_xfs_cam_v320_CamStructV3_20Test
 * Method:    createTakepictEx
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cam_v320_CamStructV3_120Test_createTakepictEx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
