/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_10_Status3_10Test */

#ifndef _Included_at_o2xfs_xfs_cim_v3_10_Status3_10Test
#define _Included_at_o2xfs_xfs_cim_v3_10_Status3_10Test
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
