/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_10_cim_Status310Test */

#ifndef _Included_at_o2xfs_xfs_v3_10_cim_Status310Test
#define _Included_at_o2xfs_xfs_v3_10_cim_Status310Test
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
