/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_10_idc_SetGuidlight310Test */

#ifndef _Included_at_o2xfs_xfs_v3_10_idc_SetGuidlight310Test
#define _Included_at_o2xfs_xfs_v3_10_idc_SetGuidlight310Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_10_idc_SetGuidlight310Test
 * Method:    buildSetGuidlight310
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_110_idc_SetGuidlight3110Test_buildSetGuidlight3110
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
