/*
 * Copyright (c) 2017, Andreas Fagschlunger. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_ctapi_CTAPI */

#ifndef _Included_at_o2xfs_ctapi_CTAPI
#define _Included_at_o2xfs_ctapi_CTAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    loadLibrary0
 * Signature: (Lat/o2xfs/win32/ZSTR;)Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_ctapi_CTAPI_loadLibrary0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    getFunctionAddress0
 * Signature: (Lat/o2xfs/win32/Pointer;Lat/o2xfs/win32/ZSTR;)Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_ctapi_CTAPI_getFunctionAddress0
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    init0
 * Signature: (Lat/o2xfs/win32/Pointer;Lat/o2xfs/win32/USHORT;Lat/o2xfs/win32/USHORT;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_ctapi_CTAPI_init0
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    data0
 * Signature: (Lat/o2xfs/win32/Pointer;Lat/o2xfs/win32/USHORT;Lat/o2xfs/win32/UINT8;Lat/o2xfs/win32/UINT8;Lat/o2xfs/win32/ByteArray;Lat/o2xfs/win32/USHORT;Lat/o2xfs/win32/ByteArray;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_ctapi_CTAPI_data0
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    close0
 * Signature: (Lat/o2xfs/win32/Pointer;Lat/o2xfs/win32/USHORT;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_ctapi_CTAPI_close0
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_ctapi_CTAPI
 * Method:    freeLibrary0
 * Signature: (Lat/o2xfs/win32/Pointer;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_ctapi_CTAPI_freeLibrary0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif