/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_00_idc_CardData3Test */

#ifndef _Included_at_o2xfs_xfs_v3_00_idc_CardData3Test
#define _Included_at_o2xfs_xfs_v3_00_idc_CardData3Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_00_idc_CardData3Test
 * Method:    buildCardData3
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_100_idc_CardData3Test_buildCardData3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
