/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_30_GetAllItemsInfo3_30Test */

#ifndef _Included_at_o2xfs_xfs_cim_v3_30_GetAllItemsInfo3_30Test
#define _Included_at_o2xfs_xfs_cim_v3_30_GetAllItemsInfo3_30Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cim_v3_30_GetAllItemsInfo3_30Test
 * Method:    buildGetAllItemsInfo3_30
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cim_v3_130_GetAllItemsInfo3_130Test_buildGetAllItemsInfo3_130
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
