/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_util_MessageHandler */

#ifndef _Included_at_o2xfs_xfs_util_MessageHandler
#define _Included_at_o2xfs_xfs_util_MessageHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_util_MessageHandler
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_util_MessageHandler_init
  (JNIEnv *, jclass);

/*
 * Class:     at_o2xfs_xfs_util_MessageHandler
 * Method:    run0
 * Signature: (Lat/o2xfs/win32/Type;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_util_MessageHandler_run0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_util_MessageHandler
 * Method:    close0
 * Signature: (Lat/o2xfs/win32/Type;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_util_MessageHandler_close0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
