/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_conf_O2XfsConf */

#ifndef _Included_at_o2xfs_xfs_conf_O2XfsConf
#define _Included_at_o2xfs_xfs_conf_O2XfsConf
#ifdef __cplusplus
extern "C" {
#endif
#undef at_o2xfs_xfs_conf_O2XfsConf_SIZE_LIMIT
#define at_o2xfs_xfs_conf_O2XfsConf_SIZE_LIMIT 256L
/*
 * Class:     at_o2xfs_xfs_conf_O2XfsConf
 * Method:    wfmCloseKey0
 * Signature: (Lat/o2xfs/win32/Type;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_xfs_conf_O2XfsConf_wfmCloseKey0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_conf_O2XfsConf
 * Method:    wfmOpenKey0
 * Signature: (Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_xfs_conf_O2XfsConf_wfmOpenKey0
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_conf_O2XfsConf
 * Method:    wfmQueryValue0
 * Signature: (Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_xfs_conf_O2XfsConf_wfmQueryValue0
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_conf_O2XfsConf
 * Method:    wfmEnumKey0
 * Signature: (Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_xfs_conf_O2XfsConf_wfmEnumKey0
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     at_o2xfs_xfs_conf_O2XfsConf
 * Method:    wfmEnumValue0
 * Signature: (Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;Lat/o2xfs/win32/Type;)I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_xfs_conf_O2XfsConf_wfmEnumValue0
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
