/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_00_CIMNoteIdsTest */

#ifndef _Included_at_o2xfs_xfs_cim_v3_00_CIMNoteIdsTest
#define _Included_at_o2xfs_xfs_cim_v3_00_CIMNoteIdsTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cim_v3_00_CIMNoteIdsTest
 * Method:    foobar
 * Signature: (Lat/o2xfs/xfs/cim/v3_00/CIMNoteIds;)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_cim_v3_100_CIMNoteIdsTest_foobar
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
