/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_00_P6Info3Test */

#ifndef _Included_at_o2xfs_xfs_cim_v3_00_P6Info3Test
#define _Included_at_o2xfs_xfs_cim_v3_00_P6Info3Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cim_v3_00_P6Info3Test
 * Method:    buildP6Info3
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cim_v3_100_P6Info3Test_buildP6Info3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
