/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_20_idc_Form320Test */

#ifndef _Included_at_o2xfs_xfs_v3_20_idc_Form320Test
#define _Included_at_o2xfs_xfs_v3_20_idc_Form320Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_20_idc_Form320Test
 * Method:    buildForm320
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_v3_120_idc_Form3120Test_buildForm3120
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
