/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_idc_v3_20_Status3_20Test */

#ifndef _Included_at_o2xfs_xfs_idc_v3_20_Status3_20Test
#define _Included_at_o2xfs_xfs_idc_v3_20_Status3_20Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_idc_v3_20_Status3_20Test
 * Method:    buildStatus3_20
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_idc_v3_120_Status3_120Test_buildStatus3_120
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
