/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_Sizeof */

#ifndef _Included_at_o2xfs_win32_Sizeof
#define _Included_at_o2xfs_win32_Sizeof
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_win32_Sizeof
 * Method:    sizeofLpvoid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_o2xfs_win32_Sizeof_sizeofLpvoid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
