/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_20_DeviceLockStatus3_20Test */

#ifndef _Included_at_o2xfs_xfs_cim_v3_20_DeviceLockStatus3_20Test
#define _Included_at_o2xfs_xfs_cim_v3_20_DeviceLockStatus3_20Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cim_v3_20_DeviceLockStatus3_20Test
 * Method:    buildDeviceLockStatus3_20
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cim_v3_120_DeviceLockStatus3_120Test_buildDeviceLockStatus3_120
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
