/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_INTTest */

#ifndef _Included_at_o2xfs_win32_INTTest
#define _Included_at_o2xfs_win32_INTTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_win32_INTTest
 * Method:    test
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_win32_INTTest_test
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
