/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_Type */

#ifndef _Included_at_o2xfs_win32_Type
#define _Included_at_o2xfs_win32_Type
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_win32_Type
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_win32_Type_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
