/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_Type */

#ifndef _Included_at_o2xfs_win32_Type
#define _Included_at_o2xfs_win32_Type
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_win32_Type
 * Method:    address
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_at_o2xfs_win32_Type_address
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
