/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_cim_v3_10_P6CompareResult3_10Test */

#ifndef _Included_at_o2xfs_xfs_cim_v3_10_P6CompareResult3_10Test
#define _Included_at_o2xfs_xfs_cim_v3_10_P6CompareResult3_10Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_cim_v3_10_P6CompareResult3_10Test
 * Method:    buildP6CompareResult3_10
 * Signature: ()Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_xfs_cim_v3_110_P6CompareResult3_110Test_buildP6CompareResult3_110
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
