/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_impl_Win32Buffer */

#ifndef _Included_at_o2xfs_win32_impl_Win32Buffer
#define _Included_at_o2xfs_win32_impl_Win32Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_win32_impl_Win32Buffer
 * Method:    allocate0
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_win32_impl_Win32Buffer_allocate0
  (JNIEnv *, jobject, jint);

/*
 * Class:     at_o2xfs_win32_impl_Win32Buffer
 * Method:    get0
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_win32_impl_Win32Buffer_get0
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     at_o2xfs_win32_impl_Win32Buffer
 * Method:    put0
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_win32_impl_Win32Buffer_put0
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     at_o2xfs_win32_impl_Win32Buffer
 * Method:    subBuffer0
 * Signature: ([BII)Lat/o2xfs/win32/Buffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_win32_impl_Win32Buffer_subBuffer0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     at_o2xfs_win32_impl_Win32Buffer
 * Method:    free0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_win32_impl_Win32Buffer_free0
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
