/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_win32_Pointer */

#ifndef _Included_at_o2xfs_win32_Pointer
#define _Included_at_o2xfs_win32_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#undef at_o2xfs_win32_Pointer_SIZE
#define at_o2xfs_win32_Pointer_SIZE 4L
/*
 * Class:     at_o2xfs_win32_Pointer
 * Method:    get
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_at_o2xfs_win32_Pointer_get
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
